### ISSUE TITLE
Strategy pattern implementation

### ISSUE THREAD

**Issue by mboom** [mboom/TI2206#74]
There is a design, almost complete, for the implementation of level strategies. The normal way to do this is using an Strategy interface. In my design it seems better to use an abstract class instead of an interface because some functions should be the same for every design.Is this allowed in the strategy pattern?

**Comment by lvdoorn** [comment]
Abstract classes and interfaces are very similar, the only difference is that abstract classes can have attributes. If you want to specify subclasses' attributes, then use and abstract class, otherwise an interface would do. Another solution is to have the abstract class implement an interface (thus allowing for multiple abstract classes in the future).
